version: '3.7'

services:
  db:
    build: .
    container_name: socialWebPrototype
    image: postgres:latest
    volumes:
      - socialWebPrototype:/var/lib/postgresql
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports:
      - '3307:3307'

volumes:
  socialWebPrototype: